version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Docker build
          command: docker-compose build 
      - run:
          name: Docker compose 
          command: docker-compose up

